# Generated by Django 5.0.2 on 2024-02-14 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=500)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='ChatFiles/')),
                ('editor_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_from', to='Guest.tbl_editor')),
                ('editor_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_to', to='Guest.tbl_editor')),
                ('photographer_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photographer_from', to='Guest.tbl_photographer')),
                ('photographer_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photographer_to', to='Guest.tbl_photographer')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_ebooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booked_date', models.DateField(auto_now_add=True)),
                ('payment_status', models.CharField(default=0, max_length=10)),
                ('payment_amount', models.IntegerField(default=0)),
                ('ebooking_discription', models.CharField(max_length=100)),
                ('ebooking_vstatus', models.CharField(default=0, max_length=10)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_editor')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_photographer')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_mbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booked_date', models.DateField(auto_now_add=True)),
                ('payment_status', models.CharField(default=0, max_length=10)),
                ('payment_amount', models.CharField(default=0, max_length=10)),
                ('mbooking_discription', models.CharField(max_length=10)),
                ('mbooking_vstatus', models.CharField(default=0, max_length=10)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_model')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_photographer')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=50)),
                ('post_image', models.FileField(upload_to='PostDocs/')),
                ('post_caption', models.CharField(max_length=100)),
                ('post_amount', models.CharField(max_length=100)),
                ('paid_status', models.CharField(default=0, max_length=10)),
                ('p_status', models.CharField(default=0, max_length=10)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_editor')),
                ('photographer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_photographer')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_addgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addgallery_caption', models.CharField(max_length=100)),
                ('addgallery_image', models.FileField(upload_to='GalleryDocs/')),
                ('p_status', models.CharField(default=0, max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Photographers.tbl_post')),
            ],
        ),
    ]
