# Generated by Django 5.0.2 on 2024-02-14 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(max_length=50)),
                ('editor_email', models.CharField(max_length=50)),
                ('editor_contact', models.CharField(max_length=50)),
                ('editor_address', models.CharField(max_length=100)),
                ('editor_gender', models.CharField(max_length=50)),
                ('editor_password', models.CharField(max_length=50)),
                ('editor_photo', models.FileField(upload_to='EditorDocs/')),
                ('editor_proof', models.FileField(upload_to='EditorDocs/')),
                ('editor_vstatus', models.CharField(default=0, max_length=10)),
                ('editor_doj', models.DateField(auto_now_add=True)),
                ('ecat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_editorcategory')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('model_email', models.CharField(max_length=50)),
                ('model_contact', models.CharField(max_length=50)),
                ('model_address', models.CharField(max_length=100)),
                ('model_gender', models.CharField(max_length=50)),
                ('model_password', models.CharField(max_length=50)),
                ('model_photo', models.FileField(upload_to='ModelDocs/')),
                ('model_proof', models.FileField(upload_to='ModelDocs/')),
                ('model_vstatus', models.CharField(default=0, max_length=10)),
                ('model_doj', models.DateField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photographer_name', models.CharField(max_length=50)),
                ('photographer_email', models.CharField(max_length=50)),
                ('photographer_contact', models.CharField(max_length=50)),
                ('photographer_address', models.CharField(max_length=100)),
                ('photographer_gender', models.CharField(max_length=50)),
                ('photographer_password', models.CharField(max_length=50)),
                ('photographer_photo', models.FileField(upload_to='PhotographerDocs/')),
                ('photographer_proof', models.FileField(upload_to='PhotographerDocs/')),
                ('photographer_vstatus', models.CharField(default=0, max_length=10)),
                ('photographer_doj', models.DateField(auto_now_add=True)),
                ('pcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_photographercategory')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=100)),
                ('user_gender', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_photo', models.FileField(upload_to='UserDocs/')),
                ('user_doj', models.DateField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
